### ISSUE TITLE
[E] pipe_in: error on select: -1, errno: 9

### ISSUE THREAD

**Issue by Petru-design** [heshiming/jauto#1]
I am getting the following error after the app starts: "[E] pipe_in: error on select: -1, errno: 9". The error is continuously printed to the console. Hence I cannot provide any other command, as it seems the pipe is fully busy due to this error

I have 2 almost identical setups, and the error only appears on one of them. 
Both setups are Ubuntu 20.04 x64, with minor variations due to time of build

Working setup:
5.10.102.1-microsoft-standard-WSL2
openjdk 11.0.15 2022-04-19

Error setup:
linux 5.4.0-72-generic
openjdk 11.0.16 2022-07-19

Error log (after calling app.sh):
````log
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
2022-08-18 22:07:20 [I] ----------------
2022-08-18 22:07:20 [I]  jauto started. 
2022-08-18 22:07:20 [I] ----------------
2022-08-18 22:07:20 [I] pipe_in: going with input path: [/tmp/jauto.in]
2022-08-18 22:07:20 [I] received command ping, but processing is disabled, ignored
2022-08-18 22:07:20 [I] jauto command processing enabled
2022-08-18 22:07:20 [I] file_out: discarded command ping due to no output or output_path
log4j:WARN No appenders could be found for logger (jetbrains.mps.util.ClassPathReader).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
2022-08-18 22:07:25 [E] pipe_in: error on select: -1, errno: 9
2022-08-18 22:07:25 [E] pipe_in: error on select: -1, errno: 9
2022-08-18 22:07:25 [E] pipe_in: error on select: -1, errno: 9
2022-08-18 22:07:25 [E] pipe_in: error on select: -1, errno: 9
2022-08-18 22:07:25 [E] pipe_in: error on select: -1, errno: 9
2022-08-18 22:07:25 [E] pipe_in: error on select: -1, errno: 9

....
````
(continues until forced kill)

Excluding the error logs, the other logs are identical between the 2 setups, with only other difference being the info message regarding the ping command provided by Jauto.
I do not understand what causes the issue, as both use the same version of the app, same version of Jauto, and almost same version of jdk. Can you please assist?

**Comment by heshiming** [comment]
According to [the reference](https://unix.superglobalmegacorp.com/Net2/newsrc/sys/errno.h.html) , error 9 is EBADF or Bad File Descriptor. It says `/tmp/jauto.in` is not a proper FIFO/pipe. It's happening in [very early of the message loop](https://github.com/heshiming/jauto/blob/master/src/pipe_in.c#L78) so really nothing else of the program can work.

Several reasons can cause this but ultimately all point to the wellness of the pipe `/tmp/jauto.in`:

1. If you are mounting `/tmp` inside a container to a host directory, or network directory, try not to do so.
2. Try to manually and forcefully delete `/tmp/jauto.in` to see if it's a permission problem. In my own experience previous process leftover "pipe files" are ok, but it doesn't hurt to try anew.
3. Check if there is a permission issue accessing `/tmp` from your host program.
4. Check if another process is already running with JAuto, and thus occupying this pipe.

**Comment by Petru-design** [comment]
Thank you for fast reply. It was indeed a permission problem.  

Initial `/tmp/jauto.in` permisions: `-rw-rw-r--`
Tried to change permissions to `-rwxrwxrwx`, but this didnt help
After deleting the file, it was recreated with the following permissions: `prw-rw-r--`, and the error is gone.
